# Generated by Django 4.2.4 on 2023-08-31 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="payment_method",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order", to="users.userpayment"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.orderdetail"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="order_items", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="shipping_address",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="users.useraddress"
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="orders", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
