# Generated by Django 4.2.4 on 2023-09-03 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("orders", "0003_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpayment",
            name="payment_method",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order", to="users.userpayment"
            ),
        ),
    ]
